### ISSUE TITLE
Modelo de negocios 

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-buscadores-de-datos#1]
[El Business Model Canvas.pdf](https://github.com/user-attachments/files/17122091/El.Business.Model.Canvas.pdf)

*Roldan Uriel Arcadio Avila 
*Ariadna Monserrat Lopez Aparicio

**Comment by evelyn-santiago** [comment]
20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
